plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common:common-monitoring')
    implementation project(':common:common-web')
    implementation project(':common:common-jpa')

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

tasks.named('jar') {
    enabled = false
}
