plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    // Spring Security의 crypto
    implementation 'org.springframework.security:spring-security-crypto'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    implementation 'org.springframework.boot:spring-boot-starter-validation'
}
