plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common:common-monitoring')
    implementation project(':common:common-web')
    implementation project(':common:common-jpa')

    // Spring Security의 crypto
    implementation 'org.springframework.security:spring-security-crypto'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0' // JWT API
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0' // 실제 JWT 구현체
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0' // Claim을 JSON으로 변경

    // PostgresSQL
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

//plain jar 생성 false
tasks.named('jar') {
    enabled = false
}
