# 공통 설록
server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service

# Profile을 주지 않으면 local, prod를 주면 prod로.
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: read-only

# JWT 설정 추가
auth:
  jwt:
    issuer: ${JWT_ISSUER:dear-identity-service}
    secret: ${JWT_SECRET}
