# 운영 관리 포트의 Blue/Green 동적 라우팅 설정
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: commerce-product-route
              uri: http://${TARGET_CONTAINER:blue-container}:8080
              predicates:
                - Path=/api/products/**

logging:
  level:
    root: INFO