name: dear-postgres-local

services:
  commerce-postgres:
    # 임베딩 데이터 저장을 위한 pgvector Extension 추가
    image: pgvector/pgvector:pg16
    container_name: commerce-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dear
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data