management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /api/actuator

  endpoint:
    health:
      show-details: never

  metrics:
    tags:
      application: ${spring.application.name}