plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    runtimeOnly 'org.postgresql:postgresql'     // PostgreSQL

    implementation 'software.amazon.awssdk:s3:2.46.17'    // AWS S3
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
