plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common:common-monitoring')
    implementation project(':common:common-web')
    implementation project(':common:common-jpa')

    // PostgresSQL
    runtimeOnly 'org.postgresql:postgresql'

    // AWS S3
    implementation 'software.amazon.awssdk:s3:2.46.17'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

//plain jar 생성 false
tasks.named('jar') {
    enabled = false
}
